{
 "title": "ELK Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ELk Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by (cluster) (elasticsearch_cluster_health_status{cluster=\"$Cluster\", color=\"green\"}) * 2)\r\n+\r\n(sum by (cluster) (elasticsearch_cluster_health_status{cluster=\"$Cluster\", color=\"yellow\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "تعداد ایندکس‌های ساخته شده - ${Cluster}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "elasticsearch_indices_get_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "نعداد نود(ها) - {$Cluster}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "حجم ایندکس ها- ${Cluster}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes{cluster=\"$Cluster\"}/1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "نرخ حذف- ${Cluster}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Docs/s" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_total{cluster=\"$Cluster\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "نرخ ایندکسینگ- ${Cluster}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Docs/s" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$Cluster\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "نرخ جستجو- ${Cluster}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Query/s" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{cluster=\"$Cluster\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}